//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighSchoolRockOff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public int BandID { get; set; }
        public string BandName { get; set; }
        public string HighSchool { get; set; }
    }
}
