//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSRockOff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string FeaturedTrack { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public int BandID { get; set; }
    
        public virtual Band Band { get; set; }
    }
}
