//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ListID { get; set; }
        public string ListName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual List List1 { get; set; }
        public virtual List List2 { get; set; }
        public virtual List List11 { get; set; }
        public virtual List List3 { get; set; }
        public virtual List List12 { get; set; }
        public virtual List List4 { get; set; }
        public virtual List List13 { get; set; }
        public virtual List List5 { get; set; }
    }
}
